# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               A little we knew about web
tagline:             '@Jackie Zhou'
description:         '一些关于web技术的点滴'
url:                 http://www.startrill.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jackie Zhou
  url:               http://weibo.com/1905745445
  email:             sienpo@gmail.com

# Custom vars
version:             1.0.0
